# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 379af018c43dea1ed3100dab96417892e85ef25443139d9fe980661d937a78ff57a70bf2f98ae6d54ef22c393451854b1b56c3bf4dd3ce9a040ec7861ea78dcc

test:
  secret_key_base: 5aa223d437aa726101cf5d17ac379870c7f741d102c1712f082a10d0454c787b72f104bcfa3d54c1056dd401f27d3c348573c90eef623116eb86594e53d181fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
